version: '3.9'
services:
  bellalista:
    build: .
    ports:
            - "5555:5000"
    environment:
            LETSENCRYPT_MAIL: 'eff@qq7te.com'
            VIRTUAL_HOST: 'bellalista.qq7te.com'
            LETSENCRYPT_HOST: 'bellalista.qq7te.com'
    networks: 
      - webproxy

networks:
  webproxy:
    name: 'webproxy'
    external: true


