version: '3.9'
services:
  bellalista:
    build: .
    ports:
            - "5555:5000"
    environment:
            LETSENCRYPT_MAIL: ${LETSENCRYPT_MAIL}
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
    networks: 
      - webproxy

networks:
  webproxy:
    name: ${NETWORK_NAME}
    external: true


